package dev.lok1s.handoffmyvpn

import com.highcapable.yukihookapi.annotation.xposed.InjectYukiHookWithXposed
import com.highcapable.yukihookapi.hook.factory.encase
import com.highcapable.yukihookapi.hook.log.YLog
import com.highcapable.yukihookapi.hook.xposed.proxy.IYukiHookXposedInit
import dev.lok1s.handoffmyvpn.hook.ConnectivityManagerHook
import dev.lok1s.handoffmyvpn.hook.LinkPropertiesHook
import dev.lok1s.handoffmyvpn.hook.NativeLoader
import dev.lok1s.handoffmyvpn.hook.NetworkCapabilitiesHook
import dev.lok1s.handoffmyvpn.hook.NetworkInterfaceHook
import dev.lok1s.handoffmyvpn.hook.ProxyHook
import dev.lok1s.handoffmyvpn.hook.SystemPropertyHook

/**
 * # HookEntry — Module Entry Point
 *
 * This class is discovered by LSPosed/Xposed through the `xposed_init` asset file
 * that is automatically generated by YukiHookAPI's KSP processor when it sees the
 * [@InjectYukiHookWithXposed] annotation.
 *
 * ## Dynamic scope (v2)
 *
 * Unlike v1 which hard-coded a single target package, v2 uses `loadApp { ... }`
 * without a name filter.  This means hooks fire for **every** app that the user
 * has enabled in the LSPosed Manager scope tab.  The recommended scope is defined
 * in `res/values/arrays.xml` and referenced from `AndroidManifest.xml`.
 *
 * ## Hook layers
 *
 * | Layer  | Engine        | What it hides                                     |
 * |--------|---------------|---------------------------------------------------|
 * | Java   | YukiHookAPI   | VPN transport, capabilities, LinkProperties, proxy|
 * | Native | Dobby (NDK)   | /proc/self/maps, /proc/net/tcp, mounts, getifaddrs|
 */
@InjectYukiHookWithXposed
class HookEntry : IYukiHookXposedInit {

    override fun onHook() = encase {

        // ─── Java layer hooks ────────────────────────────────────────────
        // These fire for every app in the LSPosed scope.
        // No name filter → dynamic scope controlled by LSPosed Manager.

        loadApp {
            YLog.debug(msg = "HandsOffMyVPN loading into: $packageName", tag = TAG)

            // VPN network detection — core API hooks
            NetworkCapabilitiesHook.register(this)
            ConnectivityManagerHook.register(this)
            NetworkInterfaceHook.register(this)
            LinkPropertiesHook.register(this)

            // Proxy detection
            SystemPropertyHook.register(this)
            ProxyHook.register(this)

            // ── Native layer ─────────────────────────────────────────────
            // Load libhomvpn_native.so into this process.
            // JNI_OnLoad installs Dobby hooks on libc open/read/close to
            // sanitize /proc/self/maps, /proc/net/tcp, and also hooks
            // getifaddrs/if_nametoindex to hide VPN tunnel interfaces.
            NativeLoader.loadIntoProcess(this)
        }
    }

    companion object {
        private const val TAG = "HandsOffMyVPN"
    }
}
